# Add 'root' label to any root file changes
# Quotation marks are required for the leading asterisk
root:
  - changed-files:
      - any-glob-to-any-file: '*'

# Add 'AnyChange' label to any changes within the entire repository
AnyChange:
  - changed-files:
      - any-glob-to-any-file: '**'

Blog:
  - changed-files:
      - any-glob-to-any-file: ['app/Livewire/Blog/*', 'resources/views/livewire/blog/*']

News:
  - changed-files:
      - any-glob-to-any-file: ['app/Livewire/News/*', 'resources/views/livewire/news/*']

Product:
  - changed-files:
      - any-glob-to-any-file: ['app/Livewire/Product/*', 'resources/views/livewire/product/*']

Template:
  - changed-files:
      - any-glob-to-any-file: ['app/Livewire/Template/*', 'resources/views/livewire/template/*']

# Add 'Documentation' label to any changes within 'docs' folder or any subfolders
Documentation:
  - changed-files:
      - any-glob-to-any-file: ['docs/*', 'guides/*']

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
  - head-branch: ['^feature', 'feature', 'feat']
  - commit-message: ['^feature', 'feature', 'feat']

fix:
  - head-branch: ['^fix', 'fix']
  - commit-message: ['^fix', 'fix']


# Add 'release' label to any PR that is opened against the `main` branch
release:
  - base-branch: 'production'
