name: Update Pull Request Title and Description
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Nécessaire pour obtenir tous les commits

      - name: Update PR Title and Description
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMITS=$(gh pr view $PR_NUMBER --json commits --jq '.commits[].commit.message')
          TITLE=$(echo "$COMMITS" | head -n 1)
          DESCRIPTION=$(echo "$COMMITS" | tail -n +2)

          gh pr edit $PR_NUMBER --title "$TITLE" --body "$DESCRIPTION"
